name: pseudonymise
on: [push]

jobs:
  pypi:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - run: pip3 install wheel
      - uses: actions/checkout@v2
      - run:  |
         echo "__version__ = '${GITHUB_REF#refs/*/}'" > _version.py
         cat _version.py
         python3 setup.py sdist bdist_wheel
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}
